# -*- coding: utf-8 -*-
"""18 April: App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c-FGhlXO6F9tN27Zgv1nsXaM2GEmRwXZ

ML Workflow: เอาไปประยุกต์ใช้งานใน Business

- Business Framing
- Data Preperation
--> Data Mockup
- Model Training
--> Random Forest Clssification Model
- Model Evaluation
--> Accuracy/Confusion Matrix
Non-IT: หาวิชาส่งออก Model ให้ใช้งานง่ายยิ่งขึ้น
- Business Deployment
--> Model Deployment / Webapp (Gradio) / Mobile app / Interactive App

**Qustion**: Customer Churn Prediction / Suggest Campaign --> **Inactive app (Steamlit.io)**
- (Random Forest Clssification Model)
"""

import streamlit as st
import pandas as pd
import numpy as np
import os # อ่านไฟล์
from sklearn.ensemble import RandomForestClassifier

def create_mock_data(filaname='customer_churn_mock.csv'):
  np.random.seed(42)
  n_samples = 1000
  data = {
            'CustomerID': range(1, n_samples + 1),
            'Age': np.random.randint(18, 70, n_samples),
            'Tenure_Months': np.random.randint(1, 72, n_samples),
            'Monthly_Charge': np.random.uniform(500, 3000, n_samples).round(2),
            'Support_Tickets': np.random.randint(0, 6, n_samples)
            }
  df = pd.DataFrame(data)

  churn_prob = (
          (df['Support_Tickets'] * 0.12) +
          (1 / (df['Tenure_Months'] + 1)) * 0.4 +
          (df['Monthly_Charge'] / 3000) * 0.1    )
  df['Churn'] = (np.random.rand(n_samples) < churn_prob).astype(int)
  df.to_csv(filename, index=False)
  return df

@st.cache_data #เก็บ Data แบบไม่ต้องดึงมาใหม่
def train_model():
  if not os.path.exists('customer_churn_mock.csv'):
    df = create_mock_data()
  else:
    df = pd.read_csv('customer_churn_mock.csv') #ถ้าไม่มีอ่านใหม่ หา XY
  x = df.drop(['Churn', 'CustomerID'], axis=1) # Drop CustomerID from features
  y = df['Churn'] #เอา Churn อย่างเดียว

  model = RandomForestClassifier(n_estimators=100, random_state=42)
  model.fit(x, y)
  return model

model = train_model()

#การออกแบบส่วนแสดงผล (User Interface) ที่จะใช้บท Streamlit
st.set_page_config(page_title='Customer Churn Prediction', layout='wide', page_icon=":bar_chart:") # เขียนยังไงก็ได้

st.title(":bar_chart: 'Customer Churn Prediction'")
st.markdown("แอปพลิเคชั่นสำหรับทีมการตลาดเพื่อ**ประเมินความเสี่ยง** และ **จัดแคมเปญรักษาลูกค้า** เชิงรุก")
st.divider()

#การออกแบบส่วนแสดงผลแถบข้าง (Sidebar) ที่จะใช้บน Streamlit สำหรับข้อมูลนำเข้า
st.sidebar.header("กรอบข้อมูลนำเข้า")

age = st.sidebar.slider("อายุ (ปี)",18, 70, 35)
tenure = st.sidebar.slider("จำนวนเดือนที่ใช้บริการ", 1, 72, 6)
charge = st.sidebar.number_input("ค่าใช้จ่ายต่อเดือน (บาท)", 500.0, 3000.0, 1500.0)
ticket = st.sidebar.selectbox("จำนวนครั้งที่ติดต่อฝ่าย Support (Support Ticket)", [0, 1, 2, 3, 4, 5])

"""มีส่วนของ Data, Model, หน้าจอ แต่ยังขาดการแสดงผล --> รับผลของการทำนาย (Prediction)"""

#Prediction
input_data = pd.DataFrame({
    'Age': [age],
    'Tenure_Months': [tenure],
    'Monthly_Charge': [charge],
    'Support_Tickets': [ticket]
})

prediction = model.predict(input_data)[0]
probability = model.predict_proba(input_data)[0][1]

#การแสดงผลของ Prediction
st.subheader("ผลการวิเคราะห์ความเสี่ยงและข้อเสนอทางธุรกิจ")

if prediction == 1:
  st.error(f" มีความเสี่ยงสูงที่ลูกค้ารายนี้มีโอกาสยกเลิกบริการ ({probability:.1%})")

  st.markdown("ACTION PLAN")
  st.info("""
  * **Retention Offer:** ส่ง SMS มอบคูปองส่วนลด 20% สำหรับรอบบิลถัดไป
  * **Proactive Service:** ให้ทีม Customer Success โทรสอบถามปัญหาการใช้งานโดยด่วน
  * **Expected ROI:** ค่าใช้จ่ายในการโทร+ส่วนลด คุ้มค่ากว่าการหาลูกค้าใหม่)
  """)

else:
  st.error(f" มีความเสี่ยงต่ำที่ลูกค้ารายนี้มีแนวโน้มใช้งานต่อ ({probability:.1%})")

  st.markdown("ACTION PLAN")
  st.info("""
  * **Relationship Building:** ส่งอีเมลขอบคุณสำหรับการใช้งานอย่างต่อเนื่อง
  * **Cross-sell Opportunity:** เสนอแพ็กเกจเสริม (Add-on) ที่เข้ากับพฤติกรรมการใช้งาน
  """)

